
export const GET_CLOTH_REQUEST = "GET_CLOTH_REQUEST";
export const GET_CLOTH_SUCCESS = "GET_CLOTH_SUCCESS";
export const GET_CLOTH_FAILURE = "GET_CLOTH_FAILURE";

export const GET_ELECTRONICS_PRODUCT_REQUEST ="GET_ELECTRONICS_PRODUCT_REQUEST";
export const GET_ELECTRONICS_PRODUCT_SUCCESS ="GET_ELECTRONICS_PRODUCT_SUCCESS";
export const GET_ELECTRONICS_PRODUCT_FAILURE ="GET_ELECTRONICS_PRODUCT_FAILURE";
  
export const GET_Watch_REQUEST="GET_Watch_REQUEST"
export const GET_Watch_SUCCESS="GET_Watch_SUCCESS"
export const GET_Watch_FAILURE="GET_Watch_FAILURE"

export const UPDATE_Watch_REQUEST="UPDATE_Watch_REQUEST"
export const UPDATE_Watch_SUCCESS="UPDATE_Watch_SUCCESS"
export const UPDATE_Watch_FAILURE="UPDATE_Watch_FAILURE"
