export const GET_ELECTRONICS_PRODUCT_REQUEST =
  "GET_ELECTRONICS_PRODUCT_REQUEST";
export const GET_ELECTRONICS_PRODUCT_SUCCESS =
  "GET_ELECTRONICS_PRODUCT_SUCCESS";
export const GET_ELECTRONICS_PRODUCT_FAILURE =
  "GET_ELECTRONICS_PRODUCT_FAILURE";
