export const GET_CLOTH_REQUEST = "GET_CLOTH_REQUEST";
export const GET_CLOTH_SUCCESS = "GET_CLOTH_SUCCESS";
export const GET_CLOTH_FAILURE = "GET_CLOTH_FAILURE";
export const GET_ELECTRONICS_PRODUCT_REQUEST =
  "GET_ELECTRONICS_PRODUCT_REQUEST";
export const GET_ELECTRONICS_PRODUCT_SUCCESS =
  "GET_ELECTRONICS_PRODUCT_SUCCESS";
export const GET_ELECTRONICS_PRODUCT_FAILURE =
  "GET_ELECTRONICS_PRODUCT_FAILURE";
